channels:
- conda-forge
dependencies:
- python=3.10.6
- pip<=25.3
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.2
  - numpy==1.26.4
  - pandas==2.3.3
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.3
name: mlflow-env
